# NOTE: The training stage code is not tested yet.
Model:
  - Name: diffeic
    Key: DiffEIC
    Params:
      pretrained_target_rate: 0.06
    ExtParams:
      SaveRecon: true

Data:
  Train:
    Key: LICDataset
    Params:
      root: dataset/LSDIR
      transform:
        RandomCrop: 
          size: [512, 512]
        RandomHorizontalFlip: ~
  Val:
    Key: BasicImageDataset
    Params:
      root: dataset/Kodak
  Test:
    Key: BasicImageDataset
    Params:
      root: dataset/Kodak
      return_img_info: true
  BatchSize: 4

Train:
  Steps: 1_200_000
  Valinterval: 1

Env:
  Devices: [0]