Global:
  lmbda: &lmbda [256, 512, 1024, 2048]

Model:
  - Name: DVC-CompressAI
    Key: DVC
    ExtParams:
      lmbda: *lmbda

Data:
  Key: PFrameVideoDataModule
  Params:
    train_data_dir: dataset/vimeo_setuplet
    test_data_dir: dataset/UVG/images
    batch_size: 16

Train:
  Steps: 2000000
  Valinterval: 1

Env:
  Devices: [0]