# Test the pretrained generative image compression models.
Model:
  - !include model/generative/DiffC.yaml

  - !include model/generative/DiffEIC.yaml

  - !include model/generative/StableCodec.yaml

Data:
  Test:
    - Key: BasicImageDataset
      Params:
        root: dataset/Kodak
        return_img_info: true
    - Key: BasicImageDataset
      Params:
        root: dataset/CLIC2020_professional_val
        transform:
          CenterCrop:
            size: [768, 768]
        return_img_info: true

Env:
  Devices: [0]