Global:
  lmbda1: &lmbda1 [0.0018, 0.0035, 0.0067, 0.0130, 0.0250, 0.0483, 0.0932, 0.1800]
  lmbda2: &lmbda2 [0.0018, 0.0035, 0.0067, 0.0130, 0.0250, 0.0483]

Model:
  - Name: balle2016
    Key: FactorizedPrior
    Params:
      N: [128, 128, 128, 128, 128, 192, 192, 192]
      M: [192, 192, 192, 192, 192, 320, 320, 320]
    ExtParams:
      Lmbda: *lmbda1

  - Name: balle2018
    Key: ScaleHyperprior
    Params:
      N: [128, 128, 128, 128, 128, 192, 192, 192]
      M: [192, 192, 192, 192, 192, 320, 320, 320]
    ExtParams:
      Lmbda: *lmbda1

  - Name: minnen2018-meanscale
    Key: MeanScaleHyperprior
    Params:
      N: [128, 128, 128, 128, 192, 192, 192, 192]
      M: [192, 192, 192, 192, 320, 320, 320, 320]
    ExtParams:
      Lmbda: *lmbda1
  
  - Name: minnen2018-autoregressive
    Key: JointAutoregressiveHierarchicalPriors
    Params:
      N: [128, 128, 128, 128, 192, 192, 192, 192]
      M: [192, 192, 192, 192, 320, 320, 320, 320]
    ExtParams:
      Lmbda: *lmbda1

  - Name: minnen2020
    Key: ChARM
    Params:
      N: 128
      M: 192
    ExtParams:
      Lmbda: *lmbda1

  - Name: cheng2020anchor
    Key: Cheng2020Anchor
    Params:
      N: [128, 128, 128, 192, 192, 192]
    ExtParams:
      Lmbda: *lmbda1

  - Name: cheng2020attention
    Key: Cheng2020Attention
    Params:
      N: [128, 128, 128, 192, 192, 192]
    ExtParams:
      Lmbda: *lmbda1

  - Name: cheng2020checkerboard
    Key: Cheng2020AnchorCheckerboard
    Params:
      N: 192
    ExtParams:
      Lmbda: *lmbda1

  - Name: elic2022
    Key: Elic2022Official
    Params:
      N: 192
      M: 320
    ExtParams:
      Lmbda: *lmbda1


Data:
  Train:
    Key: Vimeo90kDataset
    Params:
      root: dataset/vimeo_setuplet
      transform:
        RandomCrop: 
          size: [256, 256]
        RandomHorizontalFlip: ~
      split: train
      tuplet: 7
  Val:
    Key: BasicImageDataset
    Params:
      root: dataset/Kodak
  Test:
    Key: BasicImageDataset
    Params:
      root: dataset/Kodak
  BatchSize: 16
  
Train:
  Steps: 5_000_000
  Valinterval: 1
  Benchmark: 
    - Key: BD_RATE
      Params:
        mode: 1
        baseline: "JPEG"
    - Key: BD_CURVE


Env:
  Devices: [0, 1, 2, 3]