Global:
  lmbda: &lmbda [0.0018, 0.0035, 0.0067, 0.0130, 0.0250, 0.0483, 0.0932, 0.1800]


Model:
  - Name: balle2016
    Key: FactorizedPrior
    Params:
      N: 128
      M: 192
    ExtParams:
      lmbda: *lmbda
      distortion: mse

  - Name: minnen2018
    Key: MeanScaleHyperprior
    Params:
      N: 128
      M: 192
    ExtParams:
      lmbda: *lmbda
      distortion: mse

Data:
  Key: BasicImageDataModule
  Params:
    train_data_dir: dataset/clic2020_professional_train
    test_data_dir: dataset/Kodak
    batch_size: 4

Train:
  Epoch: 100
  Valinterval: 5
  Benchmark: 
    - Key: BD_RATE
      Params:
        mode: 1
        baseline: "JPEG"
    - Key: BD_CURVE


Env:
  Devices: [0,1]