Global:
  lmbda: &lmbda [1625]

Model:
  - Key: ScaleSpaceFlow
    ExtParams:
      lmbda: *lmbda

Data:
  Key: CompressAIVideoDataModule
  Params:
    root: dataset/vimeo_setuplet
    batch_size: 4

Train:
  Epoch: 50
  Valinterval: 5

Env:
  Devices: [0]