# Template of Compressai FactorizedPrior
model:
  compound: CompressAI
  net:  # dict
    balle2017:
      key: FactorizedPrior
      params:
        N: 128
        M: 192

    minnen2018:
      key: MeanScaleHyperprior
      params:
        N: 128
        M: 192

  loss: # dict
    MSE: 
      weight: 1
    bpp: 
      weight: 1

train:
  trainer: CompressAI
  batchsize: 16
  epoch: 50
  valinterval: 5
  output: CompressAI

  trainset: 
    key: ImageDataset
    params:
      path: data/subset_8000_processed
      transform: # dict
        RandomCrop: 
          size: 256
  valset: 
    key: ImageDataset
    params:
      path: data/Kodak
  optim: 
    key: Adam
    params:
      lr: 1.0e-4
  schdr:
    key: ReduceLROnPlateau
    params:
      mode: min
  log:
    key: None
    params:
      project: CompressAI
    # name: FactorizedPrior

env:
  WANDB_API_KEY: None
  CUDA_VISIBLE_DEVICES: None