# Template of Compressai FactorizedPrior
model:
  compound: CompressAI
  net:
    balle2017:
      key: FactorizedPrior
      params:
        N: 128
        M: 192

    minnen2018:
      key: MeanScaleHyperprior
      params:
        N: 128
        M: 192

train:
  trainer: CompressAI
  batchsize: 16
  epoch: 50
  valinterval: 5
  trainset: 
    path: data/subset_8000_processed
    transform: 
      RandomCrop: 
        size: 256
  valset: 
    path: data/Kodak
  output: CompressAI
  loss:
    MSE: 1
    bpp: 1
  optim: 
    key: Adam
    params:
      lr: 1.0e-4
  schdr:
    key: ReduceLROnPlateau
    params:
      mode: min

log:
  key: None
  params:
    project: CompressAI
    # name: FactorizedPrior

env:
  WANDB_API_KEY: None
  CUDA_VISIBLE_DEVICES: None
  NUM_WORKERS: 0