# Template of Compressai FactorizedPrior
model:
  compound: CompressAI
  net: 
    key: FactorizedPrior
    params:
      N: 128
      M: 192

train:
  trainer: CompressAI
  batchsize: 16
  epoch: 1
  valinterval: 5
  trainset: 
    path: data/subset_8000_processed
    # path: data/Kodak
    transform: 
      RandomCrop: 
        size: 256
  valset: 
    path: data/Kodak
  output: output/CompressAI/FactorizedPrior
  loss:
    MSE: 1
    bpp: 1
  optim: 
    key: Adam
    params:
      lr: 1.0e-4

log:
  key: None
  params:
    project: ${net}
    name: ${}
    dir: ${train.output}
env:
  WANDB_API_KEY: None
  CUDA_VISIBLE_DEVICES: None
  NUM_WORKERS: 0