model:
  key: Compressor
  params:
    channel: 32
    k: [4096, 4096, 4096, 4096, 4096]
    m: [1, 1, 1, 1, 1]
    size: [16, 8, 8, 8, 8, 4, 4, 4, 4, 2, 2, 2, 2, 1, 1, 1, 1]
    denseNorm: true
train:
  batchSize: 4
  epoch: 20
  trainSet: E:\compress
  valSet: /mnt/sdb/SJTU_3DGS/lyx/McQuic/data/Kodak
  output: E:\compress
  loss: {"MSE": 1.0}
  optim:
    key: Adam
    params:
      lr: 1.e-4 # PSNR: 5.e-3 # don't try to tune lr, it is best
      # weight_decay: 0.0
      # use_nvlamb: true
  # schdr:
  #   # key: Placeholder
  #   key: CosineAnnealingWarmupRestarts
  #   params:
  #     first_cycle_steps: 198587 # totalimage / gpus / batchsize * epochs
  #     warmup_steps: 2000
  #     gamma: 1.0
  #     lrScaleRatio: 0.0
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
env:
  WANDB_ENABLE: false
log:
  key: wandb
  params:
    