Global:
  lmbda: &lmbda [0.0018, 0.0035, 0.0067, 0.0130, 0.0250]

Model:
  - Key: ScaleSpaceFlow
    ExtParams:
      lmbda: *lmbda
      training_mode: fast

Data:
  Key: VideoDataModule
  Params:
    train_data_dir: dataset/vimeo_setuplet
    test_data_dir: dataset/UVG/images
    batch_size: 4

Train:
  Steps: 2_000_000
  Valinterval: 10

Env:
  Devices: [0, 1, 2, 3]